### PR TITLE
Feature/logging

### PR DESCRIPTION
**Pull request by slax0rr**
Added the monolog logger as requirement to composer file, and added a PSR Logger Interface as dependency to the PodcastCrawler class. Also logged two exceptions, when searching the podcast, and when obtaining the RSS feed.

I hope this is what you wanted, if not, I am sure it's something to get you started.

### CODE REVIEW

**Comment by dorianneto** [comment]
It's exacly I wanted!

Until this weekend I'll check this PR and then merge into repository :)

Thank you for your contribute!

**Comment by dorianneto** [comment]
@slax0rr ,

It's a great contribution, but I found a little problem.

The dependency injection that you apply in main class will probably broken there applications that update this lib with your contribution.

I'm thinking hold on for a while to merge this improvement in the lib.

What you think?

**Comment by slax0rr** [comment]
@dorianneto yes, adding any sort of dependency breaks backward compatibility. The only way around this, is to make it optional. If this is something you would be ok with, I can make it optional.

**Comment by dorianneto** [comment]
The project is stopped for a while and I have intended to back to develop it soon so meanwhile, I'll close this PR.

**Pull request closed without merging**
